# - name: congigured frontend component
#   hosts: frontend
#   become: yes
#   tasks:
#   - name: disable default nignx
#     ansible.builtin.command: dnf module disable nginx -y

#   - name: enable nignx
#     ansible.builtin.command: dnf module enable nginx:1.24 -y

#   - name: install nginx
#     ansible.builtin.dnf:
#       name: nginx
#       state: present

#   - name: start and enable nginx
#     ansible.builtin.service:
#       name: nginx
#       state: started
#       enabled: yes

#   - name: remove html directory
#     ansible.builtin.file:
#       path: /usr/share/nginx/html
#       state: absent

#   - name: create html directory
#     ansible.builtin.file:
#       path: /usr/share/nginx/html
#       state: directory

#   - name: download frontend code
#     ansible.builtin.get_url:
#       url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#       dest: /tmp/frontend.zip
  
#   - name: unzip frontend code
#     ansible.builtin.unarchive:
#       src: /tmp/frontend.zip
#       dest: /usr/share/nginx/html
#       remote_src: yes

#   - name: remove default nginx File
#     ansible.builtin.file:
#       path: /etc/nginx/nginx.conf
#       state: absent

#   - name: copy roboshop nginx conf
#     ansible.builtin.copy:
#       src: nginx.conf
#       dest: /etc/nginx/nginx.conf 

#   - name: restart nginx
#     ansible.builtin.service:
#       name: nginx
#       state: restarted 
#       enabled: yes

- name: configured frontend component
  hosts: frontend
  become: yes
  tasks:
    - name: reset nginx module
      ansible.builtin.command: dnf -y module reset nginx

    - name: enable nginx module stream
      ansible.builtin.command: dnf -y module enable nginx:1.24

    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: remove html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download frontend code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend.zip

    - name: unzip frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copy roboshop nginx conf
      ansible.builtin.copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: start and enable nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
